{
 "title": "Application Restarts and Avaliability",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Nucleus Applications Restarts In the Last 10 Minutes",
   "type": "graph",
   "description": "Shows the number of restarts by hours by component",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{job=\"kube-state-metrics\", namespace=\"nucleus\"}[10m])) by (container, nucleusenv)*600",
     "legendFormat": "{{nucleusenv}} : {{container}}"
    }
   ]
  },
  {
   "title": "Background processor restarted",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{job=\"kube-state-metrics\", namespace=\"nucleus\", container=\"background-processor\"}[10m])) by (container, nucleusenv)*600",
     "legendFormat": "{{nucleusenv}} : {{container}}"
    }
   ]
  },
  {
   "title": "Nginx Applications Restarts In the last 10 minutes",
   "type": "graph",
   "description": "Shows the number of restarts by 10 minutes by component",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{job=\"kube-state-metrics\", namespace=\"linkerd\"}[10m])) by (container, nucleusenv)*600",
     "legendFormat": "{{nucleusenv}} : {{container}}"
    }
   ]
  },
  {
   "title": "Nginx Applications Restarts In the last 10 minutes",
   "type": "graph",
   "description": "Shows the number of restarts by 10 minutes by component",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{job=\"kube-state-metrics\", namespace=\"ingress-nginx\"}[10m])) by (container, nucleusenv)*600",
     "legendFormat": "{{nucleusenv}} : {{container}}"
    }
   ]
  },
  {
   "title": "Nucleus Applications Unavailable",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{kubernetes_name!=\"kube-state-metrics\"}) by (nucleusenv, deployment)",
     "legendFormat": "{{nucleusenv}} : {{deployment}}"
    }
   ]
  }
 ]
}