{
 "title": "Debug Nucleus (Useful for Devops, QE and Dev team)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Environment", "query": "label_values(nucleusenv)" }
  ]
 },
 "panels": [
  {
   "title": "Available replica set",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{kubernetes_name!=\"kube-state-metrics\",nucleusenv=\"$Environment\"}) by (deployment)\n",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Unavailable replica set",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{kubernetes_name!=\"kube-state-metrics\",nucleusenv=\"$Environment\"}) by (deployment)\n",
     "legendFormat": " {{deployment}}"
    }
   ]
  },
  {
   "title": "Memory usage (Nodes)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bits", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "  sum ((container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",io_kubernetes_container_name!=\"POD\",nucleusenv=\"$Environment\", })) by (kubernetes_io_hostname) ",
     "legendFormat": "{{ kubernetes_io_hostname }} "
    }
   ]
  },
  {
   "title": "CPU usage (Nodes)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",io_kubernetes_container_name!=\"POD\",nucleusenv=\"$Environment\", }[1m])) by (kubernetes_io_hostname) ",
     "legendFormat": "{{ kubernetes_io_hostname }} "
    }
   ]
  },
  {
   "title": "Mongo Used disks",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-node_filesystem_avail_bytes{job=~\"metrics-$Environment-*mongo.*\",mountpoint=~\"/|/data\"}/node_filesystem_size_bytes{job=~\"metrics-$Environment-*mongo.*\",mountpoint=~\"/|/data\"}",
     "legendFormat": "{{device}}|{{job}}"
    }
   ]
  },
  {
   "title": "Memory (Mongo)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "decmbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_memory{job=~\"metrics-$Environment-(.*)-rs-(.*)\",type=~\"resident|virtual\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Mongod Global Lock Current Queue",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "decmbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_global_lock_current_queue{job=~\"metrics-$Environment-(.*)-rs-(.*)\"}",
     "legendFormat": "Lock {{type}}"
    }
   ]
  },
  {
   "title": "Disk IO Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{job=~\"metrics-$Environment-mongo(.*)-node\",  }[5m])",
     "legendFormat": "{{device}}|{{job}}"
    }
   ]
  },
  {
   "title": "Open Connections (Ingestion)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 47 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(mongodb_mongod_connections{job=~\"metrics-$Environment-(.*)-rs-ingestion\",state=\"current\"})"
    }
   ]
  },
  {
   "title": "Open Connections (Nucleus)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 50 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(mongodb_mongod_connections{job=~\"metrics-$Environment-(.*)-rs-nucleus\",state=\"current\"})"
    }
   ]
  },
  {
   "title": "image-data-service (CPU)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"nucleus\",image!=\"\",nucleusenv=\"$Environment\",name=~\"^k8s_.*\",io_kubernetes_container_name!=\"POD\",pod=~\"image-data.*$\"}[1m])) by (pod) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "image-data-service (Memory)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",nucleusenv=\"$Environment\",pod_name=~\"image-data-service.*\"}) by (pod_name,kubernetes_io_hostname)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Edge-server-ddp (CPU)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"nucleus\",image!=\"\",nucleusenv=\"$Environment\",name=~\"^k8s_.*\",io_kubernetes_container_name!=\"POD\",pod=~\"edge-server-ddp-.*$\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Edge server ddp (Memory)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",nucleusenv=\"$Environment\",pod_name=~\"edge-server-ddp.*\"}) by (pod_name,kubernetes_io_hostname)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "background-processor (CPU)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"nucleus\",image!=\"\",nucleusenv=\"$Environment\",name=~\"^k8s_.*\",io_kubernetes_container_name!=\"POD\",pod=~\"background-processor.*$\"}[1m])) by (pod) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "background-processor (Memory)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",nucleusenv=\"$Environment\",pod_name=~\"background-processor.*\"}) by (pod_name,kubernetes_io_hostname)",
     "legendFormat": "real: {{kubernetes_io_hostname }} | {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Apps Restart",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(kube_pod_container_status_restarts_total{job=\"kube-state-metrics\",container=~\"edge-server-ddp\", nucleusenv=\"$Environment\",}[1h])))*3600",
     "legendFormat": "Edge-server-ddp"
    },
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{job=\"kube-state-metrics\",container=~\"image-data-service\", nucleusenv=\"$Environment\",}[1h]))*3600",
     "legendFormat": "Image-data-service"
    },
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{job=\"kube-state-metrics\",container=~\"background-processor\", nucleusenv=\"$Environment\",}[1h]))*3600",
     "legendFormat": "Background-processor"
    }
   ]
  }
 ]
}