{
 "title": "Nucleus - HTTP Up Status",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Environment", "query": "label_values(nucleusenv)" }
  ]
 },
 "panels": [
  {
   "title": "edge-server-ddp",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", deployment=\"edge-server-ddp\",direction=\"inbound\",namespace=\"nucleus\",nucleusenv=\"$Environment\"}[30s])) by (deployment) / sum(irate(response_total{deployment=\"edge-server-ddp\",direction=\"inbound\",namespace=\"nucleus\",nucleusenv=\"$Environment\"}[30s])) by (deployment)",
     "legendFormat": "Service: {{deployment}}"
    }
   ]
  },
  {
   "title": "image-data-service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", deployment=\"image-data-service\",direction=\"inbound\",namespace=\"nucleus\",nucleusenv=\"$Environment\"}[30s])) by (deployment) / sum(irate(response_total{deployment=\"image-data-service\",direction=\"inbound\",namespace=\"nucleus\",nucleusenv=\"$Environment\"}[30s])) by (deployment)",
     "legendFormat": "Service: {{deployment}}"
    }
   ]
  },
  {
   "title": "image-viewer-service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", deployment=\"image-viewer-service\",direction=\"inbound\",namespace=\"nucleus\",nucleusenv=\"$Environment\"}[30s])) by (deployment) / sum(irate(response_total{deployment=\"image-viewer-service\",direction=\"inbound\",namespace=\"nucleus\",nucleusenv=\"$Environment\"}[30s])) by (deployment)",
     "legendFormat": "Service: {{deployment}}"
    }
   ]
  },
  {
   "title": "meteor-ui-ddp",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", deployment=\"meteor-ui-ddp\",direction=\"inbound\",namespace=\"nucleus\",nucleusenv=\"$Environment\"}[30s])) by (deployment) / sum(irate(response_total{deployment=\"meteor-ui-ddp\",direction=\"inbound\",namespace=\"nucleus\",nucleusenv=\"$Environment\"}[30s])) by (deployment)",
     "legendFormat": "Service: {{deployment}}"
    }
   ]
  }
 ]
}