{
 "title": "Nucleus - Response Latency",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Environment", "query": "label_values(nucleusenv)" }
  ]
 },
 "panels": [
  {
   "title": "edge-server-ddp",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(response_latency_ms_bucket{deployment=\"edge-server-ddp\",direction=\"inbound\",namespace=\"nucleus\",nucleusenv=\"$Environment\"}[30s])) by (le, deployment))",
     "legendFormat": "p50: {{deployment}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{deployment=\"edge-server-ddp\",direction=\"inbound\",namespace=\"nucleus\",nucleusenv=\"$Environment\"}[30s])) by (le, deployment))",
     "legendFormat": "p95: {{deployment}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(response_latency_ms_bucket{deployment=\"edge-server-ddp\",direction=\"inbound\",namespace=\"nucleus\",nucleusenv=\"$Environment\"}[30s])) by (le, deployment))",
     "legendFormat": "p99: {{deployment}}"
    }
   ]
  },
  {
   "title": "image-data-service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(response_latency_ms_bucket{deployment=\"image-data-service\",direction=\"inbound\",namespace=\"nucleus\",nucleusenv=\"$Environment\"}[30s])) by (le, deployment))",
     "legendFormat": "p50: {{deployment}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{deployment=\"image-data-service\",direction=\"inbound\",namespace=\"nucleus\",nucleusenv=\"$Environment\"}[30s])) by (le, deployment))",
     "legendFormat": "p95: {{deployment}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(response_latency_ms_bucket{deployment=\"image-data-service\",direction=\"inbound\",namespace=\"nucleus\",nucleusenv=\"$Environment\"}[30s])) by (le, deployment))",
     "legendFormat": "p99: {{deployment}}"
    }
   ]
  },
  {
   "title": "meteor-ui-ddp",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(response_latency_ms_bucket{deployment=\"meteor-ui-ddp\",direction=\"inbound\",namespace=\"nucleus\",nucleusenv=\"$Environment\"}[30s])) by (le, deployment))",
     "legendFormat": "p50: {{deployment}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{deployment=\"meteor-ui-ddp\",direction=\"inbound\",namespace=\"nucleus\",nucleusenv=\"$Environment\"}[30s])) by (le, deployment))",
     "legendFormat": "p95: {{deployment}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(response_latency_ms_bucket{deployment=\"meteor-ui-ddp\",direction=\"inbound\",namespace=\"nucleus\",nucleusenv=\"$Environment\"}[30s])) by (le, deployment))",
     "legendFormat": "p99: {{deployment}}"
    }
   ]
  }
 ]
}