{
 "title": "Nucleus - CPU & Memory Usage",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Environment", "query": "label_values(nucleusenv)" }
  ]
 },
 "panels": [
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "image-data-service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"nucleus\",image!=\"\",nucleusenv=\"$Environment\",name=~\"^k8s_.*\",io_kubernetes_container_name!=\"POD\",pod=~\"image-data.*$\"}[1m])) by (pod) * ( 100 / sum by(pod) (kube_pod_container_resource_limits_cpu_cores{instance=\"kube-state-metrics.linkerd.svc.cluster.local:8080\",namespace=\"nucleus\",nucleusenv=\"$Environment\",pod=~\"image-data.*$\"}) )",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "edge-server-ddp",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"nucleus\",image!=\"\",nucleusenv=\"$Environment\",name=~\"^k8s_.*\",io_kubernetes_container_name!=\"POD\",pod=~\"edge-server.*$\"}[1m])) by (pod) * ( 100 / sum by(pod) (kube_pod_container_resource_limits_cpu_cores{instance=\"kube-state-metrics.linkerd.svc.cluster.local:8080\",namespace=\"nucleus\",nucleusenv=\"$Environment\",pod=~\"edge-server.*$\"}) )",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "image-viewer-service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"nucleus\",image!=\"\",nucleusenv=\"$Environment\",name=~\"^k8s_.*\",io_kubernetes_container_name!=\"POD\",pod=~\"image-viewer.*$\"}[1m])) by (pod) * ( 100 / sum by(pod) (kube_pod_container_resource_limits_cpu_cores{instance=\"kube-state-metrics.linkerd.svc.cluster.local:8080\",namespace=\"nucleus\",nucleusenv=\"$Environment\",pod=~\"image-viewer.*$\"}) )",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "meteor-ui-ddp",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"nucleus\",image!=\"\",nucleusenv=\"$Environment\",name=~\"^k8s_.*\",io_kubernetes_container_name!=\"POD\",pod=~\"meteor.*$\"}[1m])) by (pod) * ( 100 / sum by(pod) (kube_pod_container_resource_limits_cpu_cores{instance=\"kube-state-metrics.linkerd.svc.cluster.local:8080\",namespace=\"nucleus\",nucleusenv=\"$Environment\",pod=~\"meteor.*$\"}) )",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "study-rollup",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"nucleus\",image!=\"\",nucleusenv=\"$Environment\",name=~\"^k8s_.*\",io_kubernetes_container_name!=\"POD\",pod=~\"study.*$\"}[1m])) by (pod) * ( 100 / sum by(pod) (kube_pod_container_resource_limits_cpu_cores{instance=\"kube-state-metrics.linkerd.svc.cluster.local:8080\",namespace=\"nucleus\",nucleusenv=\"$Environment\",pod=~\"study.*$\"}) )",
     "legendFormat": "real: {{ kubernetes_io_hostname }} | {{ pod_name }} "
    }
   ]
  },
  {
   "title": "chunk-frame-extraction",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"nucleus\",image!=\"\",nucleusenv=\"$Environment\",name=~\"^k8s_.*\",io_kubernetes_container_name!=\"POD\",pod=~\"chunk-frame-extraction.*$\"}[1m])) by (pod) * ( 100 / sum by(pod) (kube_pod_container_resource_limits_cpu_cores{instance=\"kube-state-metrics.linkerd.svc.cluster.local:8080\",namespace=\"nucleus\",nucleusenv=\"$Environment\",pod=~\"chunk-frame-extraction.*$\"}) )",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "p10-accumulator",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"nucleus\",image!=\"\",nucleusenv=\"$Environment\",name=~\"^k8s_.*\",io_kubernetes_container_name!=\"POD\",pod=~\"p10-accumulator.*$\"}[1m])) by (pod) * ( 100 / sum by(pod) (kube_pod_container_resource_limits_cpu_cores{instance=\"kube-state-metrics.linkerd.svc.cluster.local:8080\",namespace=\"nucleus\",nucleusenv=\"$Environment\",pod=~\"p10-accumulator.*$\"}) )",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "p10-chunk",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"nucleus\",image!=\"\",nucleusenv=\"$Environment\",name=~\"^k8s_.*\",io_kubernetes_container_name!=\"POD\",pod=~\"p10-chunk.*$\"}[1m])) by (pod) * ( 100 / sum by(pod) (kube_pod_container_resource_limits_cpu_cores{instance=\"kube-state-metrics.linkerd.svc.cluster.local:8080\",namespace=\"nucleus\",nucleusenv=\"$Environment\",pod=~\"p10-chunk.*$\"}) )",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "image-viewer-service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",nucleusenv=\"$Environment\",pod_name=~\"image-viewer.*\"}) by (pod_name,kubernetes_io_hostname,nucleusenv)",
     "legendFormat": "real: {{kubernetes_io_hostname }} | {{ pod_name }}"
    }
   ]
  },
  {
   "title": "image-data-service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",nucleusenv=\"$Environment\",pod_name=~\"image-data.*\"}) by (pod_name,kubernetes_io_hostname)",
     "legendFormat": "real: {{kubernetes_io_hostname }} | {{ pod_name }}"
    }
   ]
  },
  {
   "title": "study-rollup",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",nucleusenv=\"$Environment\",pod_name=~\"study.*\"}) by (pod_name,kubernetes_io_hostname)",
     "legendFormat": "real: {{kubernetes_io_hostname }} | {{ pod_name }}"
    }
   ]
  },
  {
   "title": "edge-server-ddp",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",nucleusenv=\"$Environment\",pod_name=~\"edge.*\"}) by (pod_name,kubernetes_io_hostname)",
     "legendFormat": "real: {{kubernetes_io_hostname }} | {{ pod_name }}"
    }
   ]
  },
  {
   "title": "meteor-ui-ddp",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",nucleusenv=\"$Environment\",pod_name=~\"meteor.*\"}) by (pod_name,kubernetes_io_hostname)",
     "legendFormat": "real: {{kubernetes_io_hostname }} | {{ pod_name }}"
    }
   ]
  },
  {
   "title": "p10-accumulator",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",nucleusenv=\"$Environment\",pod_name=~\"p10-accumulator.*\"}) by (pod_name,kubernetes_io_hostname)",
     "legendFormat": "real: {{kubernetes_io_hostname }} | {{ pod_name }}"
    }
   ]
  },
  {
   "title": "p10-chunk",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",nucleusenv=\"$Environment\",pod_name=~\"p10-chunk.*\"}) by (pod_name,kubernetes_io_hostname)",
     "legendFormat": "real: {{kubernetes_io_hostname }} | {{ pod_name }}"
    }
   ]
  },
  {
   "title": "chunk-frame-extraction",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",nucleusenv=\"$Environment\",pod_name=~\"chunk-frame-extraction.*\"}) by (pod_name,kubernetes_io_hostname)",
     "legendFormat": "real: {{kubernetes_io_hostname }} | {{ pod_name }}"
    }
   ]
  }
 ]
}