{
 "title": "Response Latency",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "downsample",
    "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "deployment", "query": "label_values(deployment)" },
   { "name": "environment", "label": "environment", "query": "label_values(nucleusenv)" }
  ]
 },
 "panels": [
  { "title": "Global percentile", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Global p50 - All Deployments",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(response_latency_ms_bucket{nucleusenv=\"$environment\",deployment!~\".*(linkerd).*\"}[$interval])) by (le,deployment))",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Global p95 - All Deployments",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{nucleusenv=\"$environment\",deployment!~\".*(linkerd).*\"}[$interval])) by (le,deployment))",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  { "title": "$deployment specific", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "p50 response latency - $deployment",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(response_latency_ms_bucket{nucleusenv=\"$environment\",deployment=\"$deployment\"}[$interval])) by (le,deployment))",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "p95 response latency - $deployment",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{nucleusenv=\"$environment\",deployment=\"$deployment\"}[$interval])) by (le,deployment))",
     "legendFormat": "{{deployment}}"
    }
   ]
  }
 ]
}