---
apiVersion: v1
kind: Service
metadata:
  namespace: logging 
  name: elasticsearch-data
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/part-of: logging
    role: data
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/part-of: logging
    role: data
  ports:
  - port: 9300
    name: transport

