---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-deployment-modules
  namespace: logging
  labels:
    app.kubernetes.io/name: metricbeat
    app.kubernetes.io/part-of: logging
data:
  kubernetes.yml: |-
    - module: prometheus
      metricsets: ["collector"]
      enabled: true
      period: 10s
      hosts: ["prometheus:9090"]
      namespace: logging

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: metricbeat
  namespace: logging
  labels:
    app.kubernetes.io/name: metricbeat
    app.kubernetes.io/part-of: logging
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: metricbeat
        app.kubernetes.io/part-of: logging
    spec:
      nodeSelector:
        agentpool: monpool
      serviceAccountName: metricbeat
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: metricbeat
        image: docker.elastic.co/beats/metricbeat:7.5.2
        args: [
          "-c", "/usr/share/metricbeat/config/metricbeat.yml",
          "-e",
        ]
        env:
        - name: ELASTICSEARCH_HOST
          value: elasticsearch-client
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /usr/share/metricbeat/config/metricbeat.yml
          subPath: metricbeat.yml
          readOnly: true
        - name: modules
          mountPath: /usr/share/metricbeat/modules.d
          readOnly: true
      volumes:
      - name: config
        secret:
          secretName: metricbeat-config
          defaultMode: 0600
      - name: modules
        configMap:
          defaultMode: 0600
          name: metricbeat-deployment-modules

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: metricbeat
subjects:
  - kind: ServiceAccount
    name: metricbeat
    namespace: logging
roleRef:
  kind: ClusterRole
  name: metricbeat
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: metricbeat
  labels:
    app.kubernetes.io/name: metricbeat
    app.kubernetes.io/part-of: logging
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - namespaces
      - events
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions"]
    resources:
      - replicasets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources:
      - statefulsets
      - deployments
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - ""
    resources:
      - nodes/stats
    verbs:
      - get

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metricbeat
  namespace: logging
  labels:
    app.kubernetes.io/name: metricbeat
    app.kubernetes.io/part-of: logging
