---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: logging
  name: elasticsearch-data-config
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/part-of: logging
    role: data
data:
  elasticsearch.yml: |-
    xpack.license.self_generated.type: basic
    xpack.security.enabled: true

    cluster.name: ${CLUSTER_NAME}
    node.name: ${NODE_NAME}
    discovery.seed_hosts: ${NODE_LIST}
    cluster.initial_master_nodes: ${MASTER_NODES}

    network.host: ${NETWORK_HOST}

    node:
      master: false
      data: true
      ingest: false

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default-retain
parameters:
  cachingmode: ReadOnly
  kind: Managed
  storageaccounttype: Standard_LRS
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
volumeBindingMode: Immediate

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elasticsearch-data-storage
  namespace: logging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
  storageClassName: default

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-data
  namespace: logging
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/part-of: logging
    role: data
spec:
  serviceName: elasticsearch-data
  replicas: 1 # scale when desired
  selector:
    matchLabels:
      app.kubernetes.io/name: elasticsearch
      app.kubernetes.io/part-of: logging
      role: data
  template:
    metadata:
      labels:
        app.kubernetes.io/name: elasticsearch
        app.kubernetes.io/part-of: logging
        role: data
    spec:
      nodeSelector:
        agentpool: esdatanodes
      tolerations:
      - key: dedicated
        operator: Equal
        value: esdata
        effect: NoSchedule
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch-data
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_NAME
          value: elasticsearch
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch
              key: elasticsearch-password
        - name: NETWORK_HOST
          value: "0.0.0.0"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_LIST
          value: elasticsearch-master-0,elasticsearch-master-1,elasticsearch-data-0.elasticsearch-data.logging.svc.cluster.local,elasticsearch-client
        - name: MASTER_NODES
          value: elasticsearch-master-0,elasticsearch-master-1
        - name: ES_JAVA_OPTS
          value: -Xms7g -Xmx7g
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        resources:
          limits:
            cpu: 1
          requests:
            memory: 14Gi
        ports:
        - containerPort: 9300
          name: transport
        volumeMounts:
        - name: elasticsearch-data-storage
          mountPath: /data
        - name: config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          readOnly: true
          subPath: elasticsearch.yml
      volumes:
      - name: config
        configMap:
          name: elasticsearch-data-config
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-data-storage
    spec:
      storageClassName: default
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 80Gi