---
- hosts: all
  become: yes
  gather_facts: False

  pre_tasks:
    - name: 'install python2'
      raw: test -e /usr/bin/python || (sudo apt-get update && sudo apt-get -y install python-simplejson)
      changed_when: False
    - setup:

  vars:
    USER: nucleus
    HOME: /usr/local/nucleus
    rootCertificate: "{{ RootCertificate }}"
    sslCertificateKey: "{{ SslCertificateKey }}"
    sslCertificate: "{{ SslCertificate }}"
    isSharedService: "false"
    ingressIp: 10.1.134.6
    proxyServerName: "central-shared"
    BOX_IP: "ProvidedByVar"
    node_exporter_version: "0.17.0"
    classCPlusOffet: "10.1.134"

  roles:
    - baselineSecurity
    - dnsmasq
    - nginx
    - proxyBase
    - fluentbit
    - prometheus

  tasks:
  - name: Generate dhparams.pem as needed
    become: yes
    shell: "{{ HOME }}/installDhParams.sh /{{ USER }}/ssl/private/"
    args:
      creates: "/{{ USER }}/ssl/private/dhparams.pem"

  - name: Copy base nginx.conf
    become: true
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
      mode: 0664

  - name: Copy proxyHttp.conf routing definitions
    become: true
    template:
      src: proxyHttp.conf.j2
      dest: /etc/nginx/conf.d/proxyHttp.conf
      mode: 0664
  
  - name: Make the streaming configuration directory.
    become: true
    file:
      path: /etc/nginx/stream-conf.d
      state: directory
      recurse: yes
    when: isSharedService == "true"

  - name: Copy proxyStream.conf routing definitions
    become: true
    template:
      src: proxyStream.conf.j2
      dest: /etc/nginx/stream-conf.d/proxyStream.conf
      mode: 0664
    when: isSharedService == "true"

  - name: Copy hosts definition
    become: true
    template:
      src: hosts.j2
      dest: /etc/hosts
      mode: 0664

  - name: Restart nginx
    become: true
    service:
      name: nginx
      state: restarted

  - name: Install the fluentbit configurations
    become: yes
    copy:
      src: "{{ item }}"
      dest: "/etc/td-agent-bit/{{ item }}"
    with_items:
      - parsers.conf
      - td-agent-bit.conf

  - name: Create /var/run/fluent directory for flb.db
    become: yes
    copy:
      src: tmpfiles.d/td-agent-bit.conf
      dest: /usr/lib/tmpfiles.d/td-agent-bit.conf

  - name: Starting fluentbit service
    become: yes
    service:
      name: td-agent-bit
      enabled: yes
      state: started

  - name: Reboot server
    become: yes
    shell: "sleep 5 && reboot"
    async: 1
    poll: 0
    ignore_errors: true

  - name: Wait for restart
    wait_for_connection:
      connect_timeout: 20
      sleep: 5
      delay: 5
      timeout: 300

