---
- hosts: all
  become: yes
  gather_facts: true

  pre_tasks:
    - name: 'install python2'
      raw: test -e /usr/bin/python || (sudo apt-get update && sudo apt-get -y install python-simplejson)
      changed_when: False
    - setup:

  vars:
    HOME: "/home/vagrant"
    NODE_VERSION: "8.11.4"
    NVM_DIR: "/home/vagrant/.nvm"
    NVM_VERSION: "0.33.11"
    TERRAFORM_VERSION: "0.12.19"
    pm2_user: "vagrant"

  roles:
    - baselineSecurity
    - geerlingguy.ntp
    - nvmAndNode
    - azureCli
    - jq
    - unzip
    - terraform
    - kubectl

  tasks:
    - name: "Download and install Python 3.6"
      become: yes
      shell: "{{ item }}"
      with_items:
        - "add-apt-repository -y ppa:deadsnakes/ppa"
        - "apt update"
        - "apt -y install python3.6"
        - "apt -y install python3.6-gdbm"
        - "update-alternatives --install /usr/bin/python3 python /usr/bin/python3.6 1"
        - "update-alternatives --set python /usr/bin/python3.6"

    - name: "Download and install AzCopy"
      become: yes
      shell: "{{ item }}"
      with_items:
        - "curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg"
        - "mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg"
        - "sh -c 'echo \"deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial main\" > /etc/apt/sources.list.d/dotnetdev.list'"
        - "apt -y update"
        - "apt -y install -y dotnet-sdk-2.0.2"
        - "wget -O azcopy.tar.gz https://aka.ms/downloadazcopy-v10-linux"
        - "tar -xf azcopy.tar.gz"
        - "cp ./azcopy_linux_amd64_*/azcopy /usr/local/bin/"

    - name: "Install pip"
      become: yes
      apt: 
        name: python-pip
        state: present

    - name: "Install pip3"
      become: yes
      shell: "{{ item }}"
      with_items:
        - "apt-get -y install python3-pip"
        - "pip3 install --upgrade pip"

    - name: "Get python modules"
      become: yes
      shell: "{{ item }}"
      with_items:
        - "pip3 install requests"
        - "pip3 install adal"
    
    - name: "Install Azure to Terrform Tool"
      become: vagrant
      git:
        repo: https://github.com/andyt530/py-az2tf
        version: 9354287f17afee057e6cfa8a081486579f3450cc
        dest: /home/vagrant/py-az2tf

    - name: "Get pwgen"
      become: yes
      apt: 
        name: pwgen
        state: present

