{
 "title": "10,000ft view",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "label": "environment", "query": "label_values(nucleusenv)" },
   {
    "name": "interval",
    "label": "downsample",
    "query": "30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "95th Percentile Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "95th Percentile Latency",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "content": "This section of the dashboard shows a green/yellow/red status for 95th percentile response latency for various services.\n#### What do these measures convey?\nThese graphs track the 95th percentile response latency.  What this means is that \"95% of the time, a request to this service took this many milliseconds or less.\"  95th percentile is a more accurate measurement when you are trying to see aberrations in performance.  If you were to graph an average, the spikes would be lost in the average, but p95 will show those spikes plainly."
  },
  {
   "title": "central-ui p95 latency",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{nucleusenv=\"$environment\",deployment=~\".*central-ui.*\"}[$interval])) by (le,deployment))"
    }
   ]
  },
  {
   "title": "Users Service p95 latency",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{nucleusenv=\"$environment\",deployment=~\".*users.*\"}[$interval])) by (le, deployment))"
    }
   ]
  },
  {
   "title": "Deployments p95 latency",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{nucleusenv=\"$environment\",deployment=~\"deployments.*\"}[$interval])) by (le,deployment))"
    }
   ]
  },
  {
   "title": "Organizations p95 latency",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{nucleusenv=\"$environment\",deployment=~\".*organizations.*\"}[$interval])) by (le,deployment))"
    }
   ]
  },
  {
   "title": "Messaging p95 latency",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 5 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{nucleusenv=\"$environment\",deployment=~\".*messaging.*\"}[$interval])) by (le,deployment))"
    }
   ]
  },
  {
   "title": "MongoDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Percentage of healthy mongo nodes, $environment",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 11 },
     "format": "percentunit",
     "valueName": "avg",
     "targets": [
      {
       "expr": "(\n  (sum(mongodb_mongod_replset_member_health{nucleusenv=\"$environment\"})) \n  / \n  avg(mongodb_mongod_replset_number_of_members{nucleusenv=\"$environment\"})\n)\n/avg(mongodb_mongod_replset_number_of_members{nucleusenv=\"$environment\"})"
      }
     ]
    },
    {
     "title": "Summed operations/sec, all mongo nodes in $environment",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(mongodb_mongod_op_counters_total{nucleusenv=\"$environment\"}[$interval])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Total document operations/sec, all mongo instances in $environment",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(mongodb_mongod_metrics_document_total{nucleusenv=\"$environment\"}[$interval])) by (state)",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Oplog Lag",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_mongod_replset_oplog_head_timestamp{nucleusenv=\"$environment\"}[$interval])",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubernetes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage by pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",io_kubernetes_container_name!=\"POD\",pod_name=~\"^(.*-deployment|.*ui-).*$\",kubernetes_io_hostname=~\"^.*$\"}[$interval])) by (pod_name,kubernetes_io_hostname)",
       "legendFormat": "real: {{ kubernetes_io_hostname }} | {{ pod_name }} "
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id!=\"/\",pod_name=~\"^(.*-deployment|.*ui-).*$\",kubernetes_io_hostname=~\"^.*$\",pod_name!=\"\"}) by (pod_name,kubernetes_io_hostname)",
       "legendFormat": "real: {{kubernetes_io_hostname }} | {{ pod_name }}"
      },
      {
       "expr": "sum ((kube_pod_container_resource_requests_memory_bytes{pod=~\"^(.*-deployment|.*ui-).*$\",node=~\"^.*$\",pod_name!=\"\"})) by (pod,node)",
       "legendFormat": "rqst: {{ node }} | {{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "UI Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "cpu usage - ui",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 13 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate(container_cpu_usage_seconds_total{nucleusenv=\"$environment\",pod_name=~\"^central-ui.*$\", kubernetes_io_hostname=~\"^.*$\", pod_name!=\"\"}[$interval])) / sum (machine_cpu_cores{nucleusenv=\"$environment\",node=~\"^.*$\"}) * 100"
      }
     ]
    },
    {
     "title": "network io - ui",
     "type": "graph",
     "gridPos": { "h": 11, "w": 21, "x": 3, "y": 13 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",pod_name=~\"^.*-ui-.*$\",kubernetes_io_hostname=~\"^.*$\"}[$interval])) by (pod_name, kubernetes_io_hostname)",
       "legendFormat": "-> {{ kubernetes_io_hostname }} | {{ pod_name }}"
      },
      {
       "expr": "- sum( rate (container_network_transmit_bytes_total{id!=\"/\",pod_name=~\"^.*-ui-.*$\",kubernetes_io_hostname=~\"^.*$\"}[$interval])) by (pod_name, kubernetes_io_hostname)",
       "legendFormat": "<- {{ kubernetes_io_hostname }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "memory usage - ui",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 19 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{nucleusenv=\"$environment\",pod_name=~\"^central-ui.*$\", kubernetes_io_hostname=~\"^.*$\", pod_name!=\"\"}) / sum (kube_node_status_allocatable_memory_bytes{nucleusenv=\"$environment\",node=~\"^.*$\"}) * 100"
      }
     ]
    }
   ]
  },
  {
   "title": "Users Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "cpu usage - users",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 14 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate(container_cpu_usage_seconds_total{nucleusenv=\"$environment\",pod_name=~\"^users-deployment.*$\", kubernetes_io_hostname=~\"^.*$\", pod_name!=\"\"}[$interval])) / sum (machine_cpu_cores{nucleusenv=\"$environment\",node=~\"^.*$\"}) * 100"
      }
     ]
    },
    {
     "title": "network io - users",
     "type": "graph",
     "gridPos": { "h": 11, "w": 21, "x": 3, "y": 14 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",pod_name=~\"^users-deployment.*$\",kubernetes_io_hostname=~\"^.*$\"}[$interval])) by (pod_name, kubernetes_io_hostname)",
       "legendFormat": "-> {{ kubernetes_io_hostname }} | {{ pod_name }}"
      },
      {
       "expr": "- sum( rate (container_network_transmit_bytes_total{id!=\"/\",pod_name=~\"^users-deployment.*$\",kubernetes_io_hostname=~\"^.*$\"}[$interval])) by (pod_name, kubernetes_io_hostname)",
       "legendFormat": "<- {{ kubernetes_io_hostname }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "memory usage - users",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 20 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{nucleusenv=\"$environment\",pod_name=~\"^users-deployment.*$\", kubernetes_io_hostname=~\"^.*$\", pod_name!=\"\"}) / sum (kube_node_status_allocatable_memory_bytes{nucleusenv=\"$environment\",node=~\"^.*$\"}) * 100"
      }
     ]
    }
   ]
  },
  {
   "title": "Deployments Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "cpu usage - deployments",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 31 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate(container_cpu_usage_seconds_total{nucleusenv=\"$environment\",pod_name=~\"^deployments-deployment.*$\", kubernetes_io_hostname=~\"^.*$\", pod_name!=\"\"}[$interval])) / sum (machine_cpu_cores{nucleusenv=\"$environment\",node=~\"^.*$\"}) * 100"
      }
     ]
    },
    {
     "title": "network io - deployments",
     "type": "graph",
     "gridPos": { "h": 11, "w": 21, "x": 3, "y": 31 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",pod_name=~\"^deployments-deployment.*$\",kubernetes_io_hostname=~\"^.*$\"}[$interval])) by (pod_name, kubernetes_io_hostname)",
       "legendFormat": "-> {{ kubernetes_io_hostname }} | {{ pod_name }}"
      },
      {
       "expr": "- sum( rate (container_network_transmit_bytes_total{id!=\"/\",pod_name=~\"^deployments-deployment.*$\",kubernetes_io_hostname=~\"^.*$\"}[$interval])) by (pod_name, kubernetes_io_hostname)",
       "legendFormat": "<- {{ kubernetes_io_hostname }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "memory usage - deployments",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 37 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{nucleusenv=\"$environment\",pod_name=~\"^deployments-deployment.*$\", kubernetes_io_hostname=~\"^.*$\", pod_name!=\"\"}) / sum (kube_node_status_allocatable_memory_bytes{nucleusenv=\"$environment\",node=~\"^.*$\"}) * 100"
      }
     ]
    }
   ]
  },
  {
   "title": "Organizations Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "cpu usage - organizations",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 43 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate(container_cpu_usage_seconds_total{nucleusenv=\"$environment\",pod_name=~\"^organizations-deployment.*$\", kubernetes_io_hostname=~\"^.*$\", pod_name!=\"\"}[$interval])) / sum (machine_cpu_cores{nucleusenv=\"$environment\",node=~\"^.*$\"}) * 100"
      }
     ]
    },
    {
     "title": "network io - organizations",
     "type": "graph",
     "gridPos": { "h": 11, "w": 21, "x": 3, "y": 43 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",pod_name=~\"^organizations-deployment.*$\",kubernetes_io_hostname=~\"^.*$\"}[$interval])) by (pod_name, kubernetes_io_hostname)",
       "legendFormat": "-> {{ kubernetes_io_hostname }} | {{ pod_name }}"
      },
      {
       "expr": "- sum( rate (container_network_transmit_bytes_total{id!=\"/\",pod_name=~\"^organizations-deployment.*$\",kubernetes_io_hostname=~\"^.*$\"}[$interval])) by (pod_name, kubernetes_io_hostname)",
       "legendFormat": "<- {{ kubernetes_io_hostname }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "memory usage - organizations",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 49 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{nucleusenv=\"$environment\",pod_name=~\"^organizations-deployment.*$\", kubernetes_io_hostname=~\"^.*$\", pod_name!=\"\"}) / sum (kube_node_status_allocatable_memory_bytes{nucleusenv=\"$environment\",node=~\"^.*$\"}) * 100"
      }
     ]
    }
   ]
  },
  {
   "title": "Messaging Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "cpu usage - messaging",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 55 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate(container_cpu_usage_seconds_total{nucleusenv=\"$environment\",pod_name=~\"^messaging-deployment.*$\", kubernetes_io_hostname=~\"^.*$\", pod_name!=\"\"}[$interval])) / sum (machine_cpu_cores{nucleusenv=\"$environment\",node=~\"^.*$\"}) * 100"
      }
     ]
    },
    {
     "title": "network io - messaging",
     "type": "graph",
     "gridPos": { "h": 11, "w": 21, "x": 3, "y": 55 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",pod_name=~\"^messaging-deployment.*$\",kubernetes_io_hostname=~\"^.*$\"}[$interval])) by (pod_name, kubernetes_io_hostname)",
       "legendFormat": "-> {{ kubernetes_io_hostname }} | {{ pod_name }}"
      },
      {
       "expr": "- sum( rate (container_network_transmit_bytes_total{id!=\"/\",pod_name=~\"^messaging-deployment.*$\",kubernetes_io_hostname=~\"^.*$\"}[$interval])) by (pod_name, kubernetes_io_hostname)",
       "legendFormat": "<- {{ kubernetes_io_hostname }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "memory usage - messaging",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 61 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{nucleusenv=\"$environment\",pod_name=~\"^messaging-deployment.*$\", kubernetes_io_hostname=~\"^.*$\", pod_name!=\"\"}) / sum (kube_node_status_allocatable_memory_bytes{nucleusenv=\"$environment\",node=~\"^.*$\"}) * 100"
      }
     ]
    }
   ]
  }
 ]
}