{
 "title": "50,000ft view",
 "tags": [ "overview" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "nucleusenv", "label": "environment", "query": "label_values(nucleusenv)" },
   { "name": "downsample", "label": "downsample", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  { "title": "$nucleusenv - Quick Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "nucleusenv" },
  {
   "title": "Max response latency, all deployments, $nucleusenv",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "format": "ms",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{nucleusenv=~\"$nucleusenv\",deployment!~\".*linkerd.*\"}[$downsample])) by (le,deployment)))"
    }
   ]
  },
  {
   "title": "MongoDB RS Health, $nucleusenv",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "((\n  (sum(mongodb_mongod_replset_member_health{nucleusenv=\"$nucleusenv\"})) \n  / \n  avg(mongodb_mongod_replset_number_of_members{nucleusenv=\"$nucleusenv\"})\n)\n/avg(mongodb_mongod_replset_number_of_members{nucleusenv=\"$nucleusenv\"}))*100"
    }
   ]
  },
  {
   "title": "Worst-Case Mongo Replica Lag, $nucleusenv",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(rate(mongodb_mongod_replset_oplog_head_timestamp{nucleusenv=\"$nucleusenv\"}[$downsample]))"
    }
   ]
  },
  {
   "title": "$nucleusenv - Drilldown",
   "type": "text",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 1 },
   "content": "<a href=\"https://$nucleusenv.nucleushealthdev.io\">Goto Site</a><br/><a href=\"https://linkerd-$nucleusenv.nucleushealthdev.io\">Goto Linkerd</a>"
  }
 ]
}